version: "3"
services:
  mongo:
    image: mongo
    volumes:
      - /data/db
  app:
    restart: always
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    links:
      - mongo
