version: "3"
services:
  mongo:
    image: mongo
    volumes:
      - /data/db
  app:
    restart: always
    image: node:10-alpine
    command: yarn dev
    working_dir: /tmp/src
    volumes:
      - .:/tmp/src
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    links:
      - mongo
